title: pyiron tutorial
author: Jan Janssen

execute:
  execute_notebooks           : off

repository:
    url                       : https://github.com/pyiron-workshop/lanl-tutorial-2025
    path_to_book              : ""

launch_buttons:
  notebook_interface          : jupyterlab
  binderhub_url               : https://mybinder.org
