name: Notebooks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.10"
        environment-file: .binder/environment.yml
        auto-activate-base: false
    - name: Tests
      shell: bash -l {0}
      run: |
        python .github/ci_support/pyironconfig.py
	conda install -c conda-forge papermill
        flux start papermill 1-getting_started_with_pyiron.ipynb 1-getting_started_with_pyiron-out.ipynb -k python3
        flux start papermill 2-data-driven-materials-science.ipynb 2-data-driven-materials-science-out.ipynb -k python3
        papermill 3-implement-new-job-classes.ipynb 3-implement-new-job-classes-out.ipynb -k python3
